# Site Information

name: Digital Humanities Research Institute at Southern Methodist University
description: Digital Humanities Research Institute at Southern Methodist University
url: https://southernmethodistuniversity.github.io/home/
baseurl: /home
title: Digital Humanities Research Institute at SMU
host-institution: SMU Libraries
host-institution-url: https://www.smu.edu/libraries
date-range: August 2-13, 2021
apply-link: https://southernmethodistuniversity.github.io/home/apply.html
author: 
  name: DHRI@SMU
  email: rmirza@smu.edu
  url: https://www.smu.edu/Libraries
  twitter: smu_libraries 
  github: https://github.com/SouthernMethodistUniversity/
  address: Fondren Library <br>6414 Robert S. Hyer Lane <br>Dallas, TX 75205 </br>
  description: DHRI at SMU is a program that is working towards building and sustaining an active community around the shared idea of Digital Humanities and Digital Scholarship. 

# A list of courses that appears on the curriculum page
# Note that link-reference should be one short, descriptive word



# A list of courses that appears on the curriculum page
# Note that link-reference should be one short, descriptive word
courses:

- name: Intro
  url:  https://github.com/SouthernMethodistUniversity/intro
  link-reference: intro 
  description: Introduction to the logistics and pedagogical underpinnings of DHRI. We will discuss expectations and structure. We will establish a working definiton of what is (or what is not) DH. This concept is to be established collaboratively and will evolve during your experience.
- name: Coding
  url: https://github.com/SouthernMethodistUniversity/coding
  link -reference: coding
  description: What do we hope to accomplish in the sessions on coding? This session will discuss how to communicate directly with your computer’s operating system using a text-based interface and is a useful first step in learning many other technical skills.
- name: Data in the Humanities
  url: https://github.com/SouthernMethodistUniversity/data
  link-reference: data
  description: What is data, and what kinds of data can be useful in your research? Attendees will participate in conversations about best practices for data management, file naming rules, sustainable data formats, and structuring data.
- name: Python
  url: https://github.com/SouthernMethodistUniversity/Text_Mining_Python
  link-reference: Text_Mining_Python
  description: Python is a programming language that can be used for a wide range of tasks, including collecting and analyzing data in a variety of formats. 
- name: Tools 
  url: https://github.com/SouthernMethodistUniversity/tools
  link-reference: tools
  description: This session will introduce DH tools. We will also discuss how to choose the best tool for your projects.
- name: Access
  url: https://github.com/SouthernMethodistUniversity/access 
  link-reference: access
  description: A discussion of issues around creating and accessing datasets; including copyright, licensing, and ethics.
- name: Project Planning
  url: https://github.com/SouthernMethodistUniversity/projectplan
  link-reference: projectplan
  description: This session will allow time to apply what we have learned throughout DHRI to your research interests.

# this tells Jekyll to build the site in the "docs"
# directory, which is ideal for hosting by GitHub Pages
destination: docs


# Files that won't be included in the compiled version of the site
exclude:
  - '*.sh'
  - CNAME
  - bower_components
  - node_modules
  - _images
  - '.*'
  - 'gulpfile.js'
  - 'build_vendor.js'
  - 'get_data.js'
  - 'README.md'

# _config.stage.yml overwrites these options when you run locally
future: false
limit_posts: 10 # Only make the last 10 posts so generating isn't slow
show_drafts: false

#required by github-pages
lsi: false # Disables the more accurate related posts
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
